name=OttoHPLite
version=1.0.0
author=YourName
maintainer=YourName <youremail@example.com>
sentence=A lightweight library for Otto HP robots using ESP32.
paragraph=A fast, minimal C++ library designed for Otto HP robots. Provides direct control over motors and onboard buzzer without unnecessary overhead.
category=Device Control
url=https://github.com/Karsp/Otto_HP_lite
architectures=esp32
includes=OttoLite.h