[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
; board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  arduino-libraries/Servo@^1.2.1
  adafruit/DHT sensor library@^1.4.6
  adafruit/Adafruit Unified Sensor@^1.1.14
  adafruit/Adafruit ADXL345@^1.2.3

lib_extra_dirs = 
    ../../../../otto_HP_lite/

upload_port = COM7
